// dailyCost = average cost per person per day in NPR (stay + food + local travel)
const destinations = [
  {
    id: 1,
    name: "Rara Lake",
    province: "Karnali",
    category: "Lake",
    hidden: true,
    image: "images/rara.jpg",
    description:
      "Nepal's largest lake, ringed by pine and juniper forest inside Rara National Park. Quiet, cold and almost untouched.",
    location: "Mugu District, Karnali",
    bestTime: "April - June, Sept - Nov",
    dailyCost: 4500,
    tips: [
      "Carry warm clothes even in summer",
      "Book flights to Talcha early",
      "Bring cash; there are no ATMs",
    ],
  },
  {
    id: 2,
    name: "Khaptad National Park",
    province: "Sudurpashchim",
    category: "Nature",
    hidden: true,
    image: "images/khaptad.jpg",
    description:
      "A high grassland plateau with meadows, temples and the ashram of Khaptad Baba. A place for slow walks and silence.",
    location: "Bajhang, Doti, Achham",
    bestTime: "March - May, Oct - Nov",
    dailyCost: 3500,
    tips: [
      "Bring a tent or book a lodge ahead",
      "Carry food supplies",
      "Get a park permit at the entrance",
    ],
  },
  {
    id: 3,
    name: "Shey Phoksundo Lake",
    province: "Karnali",
    category: "Lake",
    hidden: true,
    image: "images/phoksundo.jpg",
    description:
      "A deep turquoise lake below Himalayan cliffs in Shey Phoksundo National Park, close to Bon-po villages.",
    location: "Dolpa District, Karnali",
    bestTime: "May - June, Sept - Oct",
    dailyCost: 5500,
    tips: [
      "Restricted-area permits are needed for Upper Dolpa",
      "Allow buffer days for flight delays",
      "Respect Bon-po customs",
    ],
  },
  {
    id: 4,
    name: "Tsum Valley",
    province: "Gandaki",
    category: "Trekking",
    hidden: true,
    image: "images/tsum.jpg",
    description:
      "A sacred Buddhist valley of monasteries, stone-walled villages and mani walls near the Tibetan border.",
    location: "Gorkha District, Gandaki",
    bestTime: "March - May, Sept - Nov",
    dailyCost: 6000,
    tips: [
      "Special restricted-area permit required",
      "Hire a licensed guide",
      "Walk clockwise around mani walls",
    ],
  },
  {
    id: 5,
    name: "Bandipur",
    province: "Gandaki",
    category: "Culture",
    hidden: true,
    image: "images/bandipur.jpg",
    description:
      "A preserved Newari hill town with car-free bazaars, old brick houses and wide views of the Himalayas.",
    location: "Tanahun District, Gandaki",
    bestTime: "October - April",
    dailyCost: 3000,
    tips: [
      "Stay overnight to see the sunrise",
      "Visit Siddha Cave",
      "Wear comfortable walking shoes",
    ],
  },
  {
    id: 6,
    name: "Tansen",
    province: "Lumbini",
    category: "Culture",
    hidden: true,
    image: "images/tansen.jpg",
    description:
      "A hilltop town in Palpa known for dhaka topi weaving, Srinagar Hill views and the Kali Gandaki river below.",
    location: "Palpa District, Lumbini",
    bestTime: "September - April",
    dailyCost: 2800,
    tips: [
      "Buy dhaka fabric from local weavers",
      "Take the Srinagar Hill sunrise walk",
      "Try local sukuti and sel roti",
    ],
  },
  {
    id: 7,
    name: "Ilam",
    province: "Koshi",
    category: "Nature",
    hidden: true,
    image: "images/ilam.jpg",
    description:
      "Rolling tea gardens and misty hills in eastern Nepal, with Antu Danda's sunrise views over Kanchenjunga.",
    location: "Ilam District, Koshi",
    bestTime: "March - May, Oct - Nov",
    dailyCost: 3000,
    tips: [
      "Tour a tea estate",
      "Go to Antu Danda before dawn",
      "Roads are slippery in monsoon",
    ],
  },
  {
    id: 8,
    name: "Upper Mustang",
    province: "Gandaki",
    category: "Trekking",
    hidden: true,
    image: "images/mustang.jpg",
    description:
      "The old walled kingdom of Lo, a dry high-altitude desert of red cliffs, cave monasteries and Tibetan culture.",
    location: "Mustang District, Gandaki",
    bestTime: "May - October",
    dailyCost: 9000,
    tips: [
      "Restricted-area permit is expensive; plan for it",
      "Winds get strong in the afternoon",
      "Carry sun protection",
    ],
  },
  {
    id: 9,
    name: "Pokhara",
    province: "Gandaki",
    category: "Nature",
    hidden: false,
    image: "images/pokhara.jpg",
    description:
      "Lakeside city under the Annapurna range, popular for boating, paragliding and as a trek starting point.",
    location: "Kaski District, Gandaki",
    bestTime: "September - November",
    dailyCost: 4000,
    tips: [
      "Book paragliding in the morning",
      "Visit Phewa Lake at sunrise",
      "Very busy in October",
    ],
  },
  {
    id: 10,
    name: "Lumbini",
    province: "Lumbini",
    category: "Religious",
    hidden: false,
    image: "images/lumbini.jpg",
    description:
      "The birthplace of Lord Buddha and a UNESCO World Heritage Site with the Maya Devi Temple and monastery zone.",
    location: "Rupandehi District, Lumbini",
    bestTime: "October - March",
    dailyCost: 3500,
    tips: [
      "Rent a bicycle to cover the monastery zone",
      "Dress modestly",
      "Summer is very hot",
    ],
  },
  {
    id: 11,
    name: "Chitwan National Park",
    province: "Bagmati",
    category: "Nature",
    hidden: false,
    image: "images/chitwan.jpg",
    description:
      "Jungle safaris, one-horned rhinoceros and Bengal tigers in the Terai lowlands.",
    location: "Chitwan District, Bagmati",
    bestTime: "October - March",
    dailyCost: 5000,
    tips: [
      "Choose a guided jeep or walking safari",
      "Carry mosquito repellent",
      "Book lodges in advance",
    ],
  },
  {
    id: 12,
    name: "Kathmandu",
    province: "Bagmati",
    category: "Culture",
    hidden: false,
    image: "images/kathmandu.jpg",
    description:
      "The capital city of temples, palaces and stupas, including Pashupatinath, Swayambhunath and Patan Durbar Square.",
    location: "Kathmandu Valley, Bagmati",
    bestTime: "October - December, March - April",
    dailyCost: 4500,
    tips: [
      "Start early to avoid crowds",
      "Use ride apps for short trips",
      "Carry a mask on dusty days",
    ],
  },
];
